baseURL = 'https://nivelais.com/'
languageCode = 'en-us'
title = 'Nivelais - Router'
theme = "lynx"

[params]
title = "Nivelais"

[params.author]
name = "Nivelais"
headline = "Pick the Nivelais you're interested in"
links = [
    { quentin = { href = "https://quentin.nivelais.com/", text = "Quentin", title = "CoFounder & CTO Frak-Labs" } },
    { valery = { href = "https://valery.nivelais.com/", text = "Valery", title = "Consultant en gestion de centre aquatique" } },
]
